# fly.toml file generated for haj-imgproxy on 2022-11-06T21:11:22+01:00

app = "haj-imgproxy"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "darthsim/imgproxy:latest"

[env]
  IMGPROXY_MAX_SRC_RESOLUTION = 30
  IMGPROXY_USE_S3 = true
  IMGPROXY_TTL = 31536000
  AWS_REGION = "eu-north-1"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
