# fly.toml file generated for haj on 2022-09-05T11:15:07+02:00

app = "haj"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile.production"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "haj.metaspexet.se"
  LOGIN_HOST = "login.datasektionen.se"
  ZFINGER_URL = "d2imehpdli8mvq.cloudfront.net"
  PORT = "8080"
  IMAGE_URL = "https://d3874pm7xaa2tj.cloudfront.net"
  ZFINGER_URL = "https://d2imehpdli8mvq.cloudfront.net"
  LOGIN_URL = "https://login.datasektionen.se"
  LOGIN_FRONTEND_URL = "https://login.datasektionen.se"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 100
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
